apiVersion: 1

deleteDatasources:
  - name: VictoriaMetrics
    orgId: 1

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: http://127.0.0.1:8428
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
      prometheusType: Prometheus
      prometheusVersion: 2.24.0
    editable: true
